name: meringiii
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  hexcolor: ^3.0.1
  dropdown_button2: ^2.3.9
  get_it: ^7.6.7
  flutter_switch: ^0.3.2
  flutter_native_splash: ^2.3.11
  flutter_styled_toast: ^2.2.1
  dio: ^5.4.1
  tab_container: ^2.0.0
  carousel_slider: ^4.2.1
  equatable:
  dartz:
  hive:
  hive_flutter:
  internet_connection_checker:
  percent_indicator: ^4.2.3
  floating_bottom_navigation_bar: ^1.5.2
  http: ^1.2.1
  appinio_animated_toggle_tab: ^1.0.2
  buttons_tabbar: ^1.3.8


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/icons/icons.ttf
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
